## INTRODUCTION TO DATA SCIENCE WITH PYTHON

Data science is best defined as the cross-disciplinary set of skills that are becoming important in many applications accross industry and academia.

![image](images/Data_Science_VD.png)

## Why Python?

Python is an interpreted, dynamically-typed language with a precise and efficient syntax.

Due to its simple nature, community is mostyl focused on developing extensions for the language. Most popular packages for numerical python and data science are;

- Pandas( Provides easy manipulation of data. Grouping, aggregating, making pivot tables and much more )
- Numpy( Numpy is the linear algebra extension for python )
- SciPy( SciPy provides scientific calculation extension for python such as optimisation, statistics and other tasks )
- Scikit-Learn( scikit-learn is the most popular library in python for machine learning. In fact, for beginners,  Python + Machine Learning = scikit-learn.)
- Matplotlib( Matplotlib provides data visualisation capabilities for python. )

We will be using Python3(3.6 at the time of writing) throughout these notebooks.)

## Numpy

Even though much of the data manipulation work will be carried out using pandas. We will make a brief introduction for Numpy. Both numpy and pandas are easy to learn but hard to master modules for Data Analysis.

### Data Types in Python

Effective data-driven science and computation requires understanding how data is stored and manipulated. This section outlines and contrasts how arrays of data are handled in the Python language itself, and how NumPy improves on this. 

Users of Python are often drawn-in by its ease of use, one piece of which is dynamic typing. While a statically-typed language like C or Java requires each variable to be explicitly declared, a dynamically-typed language like Python skips this specification.

/* C code */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}

While in Python the equivalent operation could be written this way:

/Python code
result = 0
for i in range(100):
    result += i

### Lists, Arrays and Numpy Standard Data Types

In [5]:
L = list(range(10))

In [6]:
#A python list containing range of numbers from 0 to 9.
#Initial indices in python always start from 0.
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
#Check type of items in the list 
type(L[0])

int

In [10]:
#and convert them to list of strings using list comprehension.
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [11]:
type(L2[0])

str

Because of Python's dynamic typing feature not all of the items within a list must be of the same type

In [12]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

#### Numpy Arrays

Although Python has a built in array module since version 3.3. We will be using Numpy arrays; ndarray(n-dimensional array) for flexibility and speed.

Example of arrays and how they will be created. But first we will be calling numpy module thus importing necessary functions for our needs.

In [13]:
import numpy as np

In [14]:
#Example integer array
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [15]:
#If we want to explicitly set data type of the array, we can use the dtype keyword;
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Some examples of arrays and multidimensional arrays;

In [17]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [20]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.28658254, 0.39317851, 0.00886186],
       [0.30846302, 0.59262208, 0.02401153],
       [0.96556592, 0.04488687, 0.21353623]])

In [23]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.64177594, -0.11947638, -0.92882375],
       [ 0.01159997, -0.52571832,  0.03853215],
       [-1.04209022,  0.01914562,  1.24741958]])

In [24]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[9, 3, 6],
       [8, 9, 3],
       [8, 5, 0]])

In [25]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Numpy Data Types

Although most of the time we will not be dealing directly with numpy's specific data types. Sometimes it may be usefull to finetune data types for memory management in computers with RAM less than or equal to 4GB.

![dtypes](images/data-types.PNG)

## Pandas

Pandas is a newer package built on top of NumPy, and provides an efficient implementation of a DataFrame. DataFrames are essentially multidimensional arrays with attached row and column labels, and often with heterogeneous types and/or missing data. As well as offering a convenient storage interface for labeled data, Pandas implements a number of powerful data operations familiar to users of both database frameworks and spreadsheet programs.

Pandas, and in particular its Series and DataFrame objects, builds on the NumPy array structure and provides efficient access to these sorts of "data munging" tasks that occupy much of a data scientist's time.

In [27]:
import pandas as pd
pd.__version__

'0.23.0'

### Pandas Objects - Series and DataFrame

#### Series

A Pandas Series is a one-dimensional array of indexed data. Series wraps both a sequence of values and a sequence of indices, which we can access with the values and index attributes. The values are simply a familiar NumPy array.

Series object is basically interchangeable with a one-dimensional NumPy array. The essential difference is the presence of the index: while the Numpy Array has an implicitly defined integer index used to access the values, the Pandas Series has an explicitly defined index associated with the values.

This explicit index definition gives the Series object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type. 

In [28]:
#Create pandas.series object
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [29]:
#.values outputs a numpy array
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [30]:
#series with a specific index
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [33]:
#accessing data with both location and index in pandas.series
#using location
data[1]

0.5

In [34]:
#using index
data['b']

0.5

#### DataFrame

If a Series is an analog of a one-dimensional array with flexible indices, a DataFrame is an analog of a two-dimensional array with both flexible row indices and flexible column names. Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, you can think of a DataFrame as a sequence of aligned Series objects. Here, by "aligned" we mean that they share the same index.

For demonstration we are going to create 2 dictionaries and then create a dataframe from those dictionaries. Dictionaries in python are key-value stores where keys are unique identifiers.

In [35]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [36]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

For example if we want area / population of California we may simply call;

- area_dict['California']
- population['California']

In [37]:
area_dict['California']

423967

In [38]:
population['California']

38332521

In [40]:
#Now to create a DataFrame;

states = pd.DataFrame({
    'population': population,
    'area': area
})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [41]:
# Like the Series object, the DataFrame has an index attribute that 
# gives access to the index labels:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

### Indexing in Pandas DataFrame

In [42]:
# In DataFrames, when we use [<name>] syntax we are calling the respective
# column of a DataFrame.
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [43]:
# Similar to above, we can also use .<name> syntax to call. But make sure
# if you are making an assignment, use [<new_name>] = <new_value(s)> syntax

states.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [46]:
# Make new density column; population divided by area
states['density'] = states['population'] / states['area']

In [47]:
states['density']

California     90.413926
Texas          38.018740
New York      139.076746
Florida       114.806121
Illinois       85.883763
Name: density, dtype: float64

In [52]:
# As we have mentioned earlier, .values syntax extracts the data as
# numpy array.
states.values

array([[3.83325210e+07, 4.23967000e+05, 9.04139261e+01],
       [2.64481930e+07, 6.95662000e+05, 3.80187404e+01],
       [1.96511270e+07, 1.41297000e+05, 1.39076746e+02],
       [1.95528600e+07, 1.70312000e+05, 1.14806121e+02],
       [1.28821350e+07, 1.49995000e+05, 8.58837628e+01]])

In [53]:
# Indexing using .iloc indexer, we can index the underlying data just as
# if it were a numpy array.
states.iloc[:3,:2]

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

In [54]:
# Similarly using .loc indexer we acn index the underlying data using explicit
# index and column names:
states.loc[:'Illinois', :'population']

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [57]:
# Masking and any similar pattern which can be applied to numpy is applicable
# to DataFrame as well.
states.loc[states.density>100, ['population','density']]

population     density
New York    19651127  139.076746
Florida     19552860  114.806121

### Operating on Pandas DataFrame

#### Handling Missing Data

The difference between data found in many tutorials and data in the real world is that real-world data is rarely clean and homogeneous. In particular, many interesting datasets will have some amount of data missing. To make matters even more complicated, different data sources may indicate missing data in different ways. Generally, strategies revolve around one of two strategies: using a mask that globally indicates missing values, or choosing a sentinel value that indicates a missing entry.

The way in which Pandas handles missing values is constrained by its reliance on the NumPy package, which does not have a built-in notion of NA values for non-floating-point data types.

#### Pythonic Missing Data
- None( a python object, can only be used in arrays with data type 'object')
- NaN( acronym for not a number )

### Operating on Null Values

There are several useful methods for detecting, removing, and replacing null values in Pandas data structures. They are:

![nanchk](images/nan-check.PNG)

In [60]:
# Create example dataframe for querying Null Values;
data = pd.Series([1, np.nan, 'hello', None])

0        1
1      NaN
2    hello
3     None
dtype: object

In [61]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [63]:
# Query not null values and return actual values
data[data.notnull()]

0        1
2    hello
dtype: object

In [64]:
# Using .fillna() to fill na values
data.fillna(0)
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [65]:
# Please note that without inplace = True added to arguements,
# most of the pandas methods will output a new DataFrame. Whereas when
# inplace = True is given as an arguement. It actually changes the existing
# DataFrame.
data.fillna(0, inplace=True)
data

0        1
1        0
2    hello
3        0
dtype: object

### Combining Datasets: Concat and Append

#### Concat

Pandas has a function, pd.concat(), which has a similar syntax to np.concatenate. pd.concat() can be used for a simple concatenation of Series or DataFrame objects.

In [84]:
#importing custom helpers(you can find them in /utils)
from utils.dataframe import make_df

class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [69]:
#concatenation with pd.concat
#create dataframes with helper function
df1 = make_df('AB',[1,2])
df2 = make_df('AB',[3,4])

In [85]:
display('df1','df2','pd.concat([df1, df2])')

C:\Users\bkarahan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df2
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

pd.concat([df1, df2])
  employee        group  hire_date
0      Bob   Accounting        NaN
1     Jake  Engineering        NaN
2     Lisa  Engineering        NaN
3      Sue           HR        NaN
0     Lisa          NaN     2004.0
1      Bob          NaN     2008.0
2     Jake          NaN     2012.0
3      Sue          NaN     2014.0

By default, the concatenation takes place row-wise within the DataFrame (i.e., axis=0). Like np.concatenate, pd.concat allows specification of an axis along which concatenation will take place. Consider the following example:

In [76]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])

In [86]:
display('df3','df4','pd.concat([df3, df4], axis=1)')

df3
    A   B
0  A0  B0
1  A1  B1

df4
    C   D
0  C0  D0
1  C1  D1

pd.concat([df3, df4], axis=1)
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

#### Append

Because direct array concatenation is so common, Series and DataFrame objects have an append method that can accomplish the same thing in fewer keystrokes. For example, rather than calling pd.concat([df1, df2]), you can simply call df1.append(df2):

In [81]:
df1.append(df2)

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

Keep in mind that unlike the append() and extend() methods of Python lists, the append() method in Pandas does not modify the original object–instead it creates a new object with the combined data. It also is not a very efficient method, because it involves creation of a new index and data buffer. Thus, if you plan to do multiple append operations, it is generally better to build a list of DataFrames and pass them all at once to the concat() function.

### Combining Datasets: Merge and Join

One essential feature offered by Pandas is its high-performance, in-memory join and merge operations. If you have ever worked with databases, you should be familiar with this type of data interaction. The main interface for this is the pd.merge function, and we'll see few examples of how this can work in practice.

#### One-to-one joins

Perhaps the simplest type of merge expresion is the one-to-one join, which is in many ways very similar to the column-wise concatenation. As a concrete example, consider the following two DataFrames which contain information on several employees in a company:

In [87]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
display('df1', 'df2')

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df2
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [88]:
df3 = pd.merge(df1, df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

The pd.merge() function recognizes that each DataFrame has an "employee" column, and automatically joins using this column as a key. The result of the merge is a new DataFrame that combines the information from the two inputs. Notice that the order of entries in each column is not necessarily maintained: in this case, the order of the "employee" column differs between df1 and df2, and the pd.merge() function correctly accounts for this. Additionally, keep in mind that the merge in general discards the index, except in the special case of merges by index (see the left_index and right_index keywords).

#### Many-to-one joins

Many-to-one joins are joins in which one of the two key columns contains duplicate entries. For the many-to-one case, the resulting DataFrame will preserve those duplicate entries as appropriate. Consider the following example of a many-to-one join:

In [92]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
display('df3', 'df4', 'pd.merge(df3, df4)')

df3
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

df4
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

pd.merge(df3, df4)
  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

The resulting DataFrame has an aditional column with the "supervisor" information, where the information is repeated in one or more locations as required by the inputs.

#### Many-to-many joins

Many-to-many joins are a bit confusing conceptually, but are nevertheless well defined. If the key column in both the left and right array contains duplicates, then the result is a many-to-many merge. This will be perhaps most clear with a concrete example. Consider the following, where we have a DataFrame showing one or more skills associated with a particular group. By performing a many-to-many join, we can recover the skills associated with any individual person:

In [93]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                              'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux',
                               'spreadsheets', 'organization']})
display('df1', 'df5', "pd.merge(df1, df5)")

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df5
         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

pd.merge(df1, df5)
  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

These three types of joins can be used with other Pandas tools to implement a wide array of functionality. But in practice, datasets are rarely as clean as the one we're working with here. In the following section we'll consider some of the options provided by pd.merge() that enable you to tune how the join operations work.

#### Special merges with key

We've already seen the default behavior of pd.merge(): it looks for one or more matching column names between the two inputs, and uses this as the key. However, often the column names will not match so nicely, and pd.merge() provides a variety of options for handling this.

- on
- left_on
- right_on
- left_index
- right_index

In [94]:
#on
display('df1', 'df2', "pd.merge(df1, df2, on='employee')")

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df2
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

pd.merge(df1, df2, on='employee')
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [96]:
#left_on and right_on
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
display('df1', 'df3', 'pd.merge(df1, df3, left_on="employee", right_on="name")')

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df3
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

pd.merge(df1, df3, left_on="employee", right_on="name")
  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [97]:
#left_index and right_index
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
display('df1a', 'df2a')

df1a
                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

df2a
          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

In [98]:
display('df1a', 'df2a',
        "pd.merge(df1a, df2a, left_index=True, right_index=True)")

df1a
                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

df2a
          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

pd.merge(df1a, df2a, left_index=True, right_index=True)
                group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

#### Using Join types for merging

Default join type for pandas merging is 'inner'. The logic is similar to SQL joins. Other options for the how keyword are 'outer', 'left', and 'right'. An outer join returns a join over the union of the input columns, and fills in all missing values with NAs. The left join and right join return joins over the left entries and right entries, respectively. 

In [99]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])
display('df6', 'df7', 'pd.merge(df6, df7)')

df6
    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

df7
     name drink
0    Mary  wine
1  Joseph  beer

pd.merge(df6, df7)
   name   food drink
0  Mary  bread  wine

In [100]:
display('df6', 'df7', "pd.merge(df6, df7, how='outer')")

df6
    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

df7
     name drink
0    Mary  wine
1  Joseph  beer

pd.merge(df6, df7, how='outer')
     name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

In [101]:
display('df6', 'df7', "pd.merge(df6, df7, how='left')")

df6
    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

df7
     name drink
0    Mary  wine
1  Joseph  beer

pd.merge(df6, df7, how='left')
    name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

### Aggregation and Grouping

An essential piece of analysis of large data is efficient summarization: computing aggregations like sum(), mean(), median(), min(), and max(), in which a single number gives insight into the nature of a potentially large dataset.

Here the Planets dataset from seaborn will be used.

In [103]:
import seaborn as sns
sns.__version__

'0.8.1'

In [106]:
#Locally added dataset
planets = pd.read_csv("csv/planets.csv")
planets.shape

(1035, 6)

#### Simple Aggregation in Pandas

In [107]:
ser = planets.mass
ser

0        7.100
1        2.210
2        2.600
3       19.400
4       10.500
5        4.800
6        4.640
7          NaN
8       10.300
9        1.990
10       0.860
11       9.880
12       3.880
13       2.530
14       0.540
15       1.640
16       0.472
17       0.800
18       0.165
19       3.530
20         NaN
21       0.172
22       0.016
23       0.057
24       0.072
25         NaN
26         NaN
27       5.300
28       3.200
29         NaN
         ...  
1005       NaN
1006       NaN
1007       NaN
1008       NaN
1009       NaN
1010       NaN
1011       NaN
1012       NaN
1013       NaN
1014       NaN
1015       NaN
1016       NaN
1017       NaN
1018       NaN
1019       NaN
1020       NaN
1021       NaN
1022       NaN
1023       NaN
1024       NaN
1025       NaN
1026       NaN
1027       NaN
1028       NaN
1029       NaN
1030       NaN
1031       NaN
1032       NaN
1033       NaN
1034       NaN
Name: mass, Length: 1035, dtype: float64

In [108]:
ser.sum()

1353.37638

In [109]:
ser.mean()

2.6381605847953233

For a DataFrame, by default the aggregates return results within each column:

In [111]:
planets.mean()

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

By specifying the axis argument, you can instead aggregate within each row:

In [112]:
planets.mean(axis=1)

0        472.160000
1        588.586800
2        559.488000
3        492.810000
4        531.238000
5        455.206000
6        759.838000
7        704.227500
8        617.140000
9        508.316000
10       594.130000
11       478.882000
12       517.852000
13       618.722000
14       881.924000
15      3205.944000
16       403.212557
17       405.796200
18       413.215000
19      1386.412000
20       507.316635
21       457.180400
22       404.950200
23       411.719600
24       428.720400
25       532.949600
26       696.600000
27       612.836000
28       448.824000
29       683.840000
           ...     
1005     554.173410
1006     586.866408
1007     568.154275
1008     617.709743
1009     579.504295
1010     536.479896
1011     604.326250
1012     624.213975
1013     544.352988
1014     586.844523
1015     591.143323
1016     581.577856
1017     599.271513
1018     560.653605
1019     590.225919
1020     588.804186
1021     569.121048
1022     526.840008
1023     641.293794


Pandas Series and DataFrames include all of the common aggregates; in addition, there is a convenience method describe() that computes several common aggregates for each column and returns the result. Let's use this on the Planets data, for now dropping rows with missing values:

In [113]:
planets.dropna().describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

This can be a useful way to begin understanding the overall properties of a dataset. For example, we see in the year column that although exoplanets were discovered as far back as 1989, half of all known expolanets were not discovered until 2010 or after. This is largely thanks to the Kepler mission, which is a space-based telescope specifically designed for finding eclipsing planets around other stars.

The following table summarizes some other built-in Pandas aggregations:

![agg](images/aggregations.png)

#### GroupBy: Split, Apply, Combine

Simple aggregations can give you a flavor of your dataset, but often we would prefer to aggregate conditionally on some label or index: this is implemented in the so-called groupby operation. The name "group by" comes from a command in the SQL database language, but it is perhaps more illuminative to think of it in the terms first coined by Hadley Wickham of Rstats fame: split, apply, combine.

A canonical example of this split-apply-combine operation, where the "apply" is a summation aggregation, is illustrated in this figure:

![gbyfig](images/gby.png)

This makes clear what the groupby accomplishes:

- The split step involves breaking up and grouping a DataFrame depending on the value of the specified key.
- The apply step involves computing some function, usually an aggregate, transformation, or filtering, within the individual groups.
- The combine step merges the results of these operations into an output array.


While this could certainly be done manually using some combination of the masking, aggregation, and merging commands covered earlier, an important realization is that the intermediate splits do not need to be explicitly instantiated. Rather, the GroupBy can (often) do this in a single pass over the data, updating the sum, mean, count, min, or other aggregate for each group along the way. The power of the GroupBy is that it abstracts away these steps: the user need not think about how the computation is done under the hood, but rather thinks about the operation as a whole.

As a concrete example, let's take a look at using Pandas for the computation shown in this diagram. We'll start by creating the input DataFrame:

In [114]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data': range(6)}, columns=['key', 'data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

The most basic split-apply-combine operation can be computed with the groupby() method of DataFrames, passing the name of the desired key column:

In [115]:
df.groupby('key')

Notice that what is returned is not a set of DataFrames, but a DataFrameGroupBy object. This object is where the magic is: you can think of it as a special view of the DataFrame, which is poised to dig into the groups but does no actual computation until the aggregation is applied. This "lazy evaluation" approach means that common aggregates can be implemented very efficiently in a way that is almost transparent to the user.

To produce a result, we can apply an aggregate to this DataFrameGroupBy object, which will perform the appropriate apply/combine steps to produce the desired result:

In [116]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

The sum() method is just one possibility here; you can apply virtually any common Pandas or NumPy aggregation function, as well as virtually any valid DataFrame operation.

#### Aggregate, filter, transform, apply

there are more options available. In particular, GroupBy objects have aggregate(), filter(), transform(), and apply() methods that efficiently implement a variety of useful operations before combining the grouped data.

For the purpose of the following subsections, we'll use this DataFrame:

In [117]:
rng = np.random.RandomState(0)
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data1': range(6),
                   'data2': rng.randint(0, 10, 6)},
                   columns = ['key', 'data1', 'data2'])
df

key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

In [118]:
# Aggregation using different operators
df.groupby('key').aggregate(['min', np.median, max])

data1            data2           
      min median max   min median max
key                                  
A       0    1.5   3     3    4.0   5
B       1    2.5   4     0    3.5   7
C       2    3.5   5     3    6.0   9

In [119]:
# Aggregate using dictionary
df.groupby('key').aggregate({'data1': 'min',
                             'data2': 'max'})

data1  data2
key              
A        0      5
B        1      7
C        2      9

In [120]:
#Filtering
def filter_func(x):
    return x['data2'].std() > 4

display('df', "df.groupby('key').std()", "df.groupby('key').filter(filter_func)")

df
  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

df.groupby('key').std()
       data1     data2
key                   
A    2.12132  1.414214
B    2.12132  4.949747
C    2.12132  4.242641

df.groupby('key').filter(filter_func)
  key  data1  data2
1   B      1      0
2   C      2      3
4   B      4      7
5   C      5      9

The filter function should return a Boolean value specifying whether the group passes the filtering. Here because group A does not have a standard deviation greater than 4, it is dropped from the result.

While aggregation must return a reduced version of the data, transformation can return some transformed version of the full data to recombine. For such a transformation, the output is the same shape as the input. A common example is to center the data by subtracting the group-wise mean:

In [121]:
df.groupby('key').transform(lambda x: x - x.mean())

data1  data2
0   -1.5    1.0
1   -1.5   -3.5
2   -1.5   -3.0
3    1.5   -1.0
4    1.5    3.5
5    1.5    3.0

The apply() method lets you apply an arbitrary function to the group results. The function should take a DataFrame, and return either a Pandas object (e.g., DataFrame, Series) or a scalar; the combine operation will be tailored to the type of output returned.

For example, here is an apply() that normalizes the first column by the sum of the second:

In [123]:
def norm_by_data2(x):
    # x is a DataFrame of group values
    x['data1'] /= x['data2'].sum()
    return x

display('df', "df.groupby('key').apply(norm_by_data2)")

df
  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

df.groupby('key').apply(norm_by_data2)
  key     data1  data2
0   A  0.000000      5
1   B  0.142857      0
2   C  0.166667      3
3   A  0.375000      3
4   B  0.571429      7
5   C  0.416667      9

#### Grouping example

As an example of this, in a couple lines of Python code we can put all these together and count discovered planets by method and by decade.

In [125]:
decade = 10 * (planets['year'] // 10)
decade = decade.astype(str) + 's'
decade.name = 'decade'
planets.groupby(['method', decade])['number'].sum().unstack().fillna(0)

decade                         1980s  1990s  2000s  2010s
method                                                   
Astrometry                       0.0    0.0    0.0    2.0
Eclipse Timing Variations        0.0    0.0    5.0   10.0
Imaging                          0.0    0.0   29.0   21.0
Microlensing                     0.0    0.0   12.0   15.0
Orbital Brightness Modulation    0.0    0.0    0.0    5.0
Pulsar Timing                    0.0    9.0    1.0    1.0
Pulsation Timing Variations      0.0    0.0    1.0    0.0
Radial Velocity                  1.0   52.0  475.0  424.0
Transit                          0.0    0.0   64.0  712.0
Transit Timing Variations        0.0    0.0    0.0    9.0

## End note

We have covered very basics of both Pandas and NumPY. These libraries are pretty much the building blocks of everything that you may encounter during data science with python.

For more detailed information, please read the documentations of these libraries,

[Pandas documentation](https://pandas.pydata.org/pandas-docs/stable/)

[NumPY documentation](https://docs.scipy.org/doc/numpy/user/quickstart.html)